### ISSUE TITLE
Merge into Image

### ISSUE THREAD

**Issue by alexchandel** [sondrele/rust-bmp#4]
You should think about copying or merging code from this repository into [PistonDevelopers/image](https://github.com/PistonDevelopers/image). It attempts to be the end-all image library, and it could use BMP support.

**Comment by sondrele** [comment]
Thanks for the suggestion! I'll definitely look into this and create a pull request for the BMP format when time allows.

**Comment by sondrele** [comment]
The PistonDevelopers/Image project has had support for BMP for quite a while now, so I'll close this issue
