### ISSUE TITLE
BMP is rotated 90 degrees when copying from normal buffer

### ISSUE THREAD

**Issue by alexchandel** [sondrele/rust-bmp#5]
When creating a BMP from a normal image buffer, the image ends up rotated 90 degrees. This is due to how BMP is defined, but rust-bmp makes no reference to this.

rust-bmp should state clearly the coordinate convention its API follows.

**Comment by okey** [comment]
What do you mean by "a normal image buffer"? Pixels in row-major order, or column major?

**Comment by alexchandel** [comment]
Possibly row major. The kind of buffer you get from `CGDisplayGetImage` on OS X, or `BitBlt` on Window, or `XGetImage` on X11, or from decoding a PNG with piston/image. All of these were rotated when I saved them to a rust-bmp Image.

**Comment by sondrele** [comment]
Do you mean that you're copying pixel by pixel from e.g. PistonDevelopers/Image to a rust-bmp image?
I guess it would make sense that it ends up rotated if pixel (0,0) in PistonDevelopers/Image is defined to be in the upper left corner, as pixel (0,0) is defined to be in the lower left corner in rust-bmp?

I think I read somewhere that for BMP images, (0,0) is usually in the lower left corner. I do however feel like it's more logical to have it in the upper right corner. Either way, you're right that the coordinate convention for the library should be well documented.

The BMP format is to the best of my knowledge row major, and I think that's also common for most raster graphics.

**Comment by sondrele** [comment]
I defined coordinate (0,0) to be in the upper left corner, so that the image is accessed in a top-bottom row-major order when it's accessed sequentially. 
As you've already kind of pointed out, it makes more sense since this coordinate convention seams to be more widely implemented elsewhere. Thanks!
