### ISSUE TITLE
Do not panic on save() failure

### ISSUE THREAD

**Issue by alexchandel** [sondrele/rust-bmp#7]
It's inappropriate to panic on a failure to write a file, since the consumer of this library may want to handle that error. Why not just return the underlying IoResult?

**Comment by sondrele** [comment]
You're absolutely right!
All the panics should be replaced with something more useful. The `save` function can return an IoResult I suppose, but I've also been thinking about introducing a BmpResult or something similar that can be returned if `open` fails.

**Comment by sondrele** [comment]
I've published a new version of the library now.
The save-function now returns an IoResult and the open-function returns a BmpResult with a couple of more descriptive error messages.
Thanks for your feedback!
